# _config.yml

# required, replace with your own information -----
title: Defne Dilbaz
author: Defne Dilbaz
description: > 
  Electrical and Computer Engineering student at the University of Toronto. Passioante about computer hardware and quantum computing. 
baseurl: ""

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  
#---------------------------------------------------

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock

